<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="5" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[--connected to DB!!!--]]>
    </line>
    <line>
      <![CDATA[--browser launched!!!--]]>
    </line>
    <line>
      <![CDATA[--open the application!!!--]]>
    </line>
    <line>
      <![CDATA[--login to application!!!--]]>
    </line>
    <line>
      <![CDATA[createContact--TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Skipped]]>
    </line>
    <line>
      <![CDATA[--logout from application!!!--]]>
    </line>
    <line>
      <![CDATA[--login to application!!!--]]>
    </line>
    <line>
      <![CDATA[createContact--TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Skipped]]>
    </line>
    <line>
      <![CDATA[--logout from application!!!--]]>
    </line>
    <line>
      <![CDATA[--login to application!!!--]]>
    </line>
    <line>
      <![CDATA[createContact--TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Skipped]]>
    </line>
    <line>
      <![CDATA[--logout from application!!!--]]>
    </line>
    <line>
      <![CDATA[--login to application!!!--]]>
    </line>
    <line>
      <![CDATA[createContact--TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Failed]]>
    </line>
    <line>
      <![CDATA[--logout from application!!!--]]>
    </line>
    <line>
      <![CDATA[--login to application!!!--]]>
    </line>
    <line>
      <![CDATA[createOrgRecycleBin--TestScript execution started]]>
    </line>
    <line>
      <![CDATA[createOrgRecycleBin--TestScript execution successful]]>
    </line>
    <line>
      <![CDATA[--logout from application!!!--]]>
    </line>
    <line>
      <![CDATA[--browser closed!!!--]]>
    </line>
    <line>
      <![CDATA[--db disconnected!!!--]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-16T15:19:59 IST" name="Default suite" finished-at="2023-01-16T15:21:04 IST" duration-ms="65013">
    <groups>
      <group name="smoke">
        <method signature="CreateContactTest.createContact()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" name="createContact" class="testNg_TestCases.CreateContactTest"/>
        <method signature="CreateContactTest.createOrgRecycleBin()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" name="createOrgRecycleBin" class="testNg_TestCases.CreateContactTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-01-16T15:19:59 IST" name="Default test" finished-at="2023-01-16T15:21:04 IST" duration-ms="65013">
      <class name="testNg_TestCases.CreateContactTest">
        <test-method is-config="true" signature="connectDB()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:19:58 IST" name="connectDB" finished-at="2023-01-16T15:19:59 IST" duration-ms="1515" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--connected to DB!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- connectDB -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:00 IST" name="launchBrowser" finished-at="2023-01-16T15:20:13 IST" duration-ms="13145" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--browser launched!!!--]]>
            </line>
            <line>
              <![CDATA[--open the application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:13 IST" name="login" finished-at="2023-01-16T15:20:16 IST" duration-ms="3301" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--login to application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method retried="true" signature="createContact()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:16 IST" name="createContact" finished-at="2023-01-16T15:20:21 IST" duration-ms="4803" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg_TestCases.CreateContactTest.createContact(CreateContactTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createContact--TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:21 IST" name="logout" finished-at="2023-01-16T15:20:22 IST" duration-ms="1207" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--logout from application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:22 IST" name="login" finished-at="2023-01-16T15:20:24 IST" duration-ms="2028" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--login to application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method retried="true" signature="createContact()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:24 IST" name="createContact" finished-at="2023-01-16T15:20:27 IST" duration-ms="2887" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg_TestCases.CreateContactTest.createContact(CreateContactTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createContact--TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:27 IST" name="logout" finished-at="2023-01-16T15:20:29 IST" duration-ms="1972" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--logout from application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:29 IST" name="login" finished-at="2023-01-16T15:20:31 IST" duration-ms="1840" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--login to application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method retried="true" signature="createContact()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:31 IST" name="createContact" finished-at="2023-01-16T15:20:34 IST" duration-ms="2688" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg_TestCases.CreateContactTest.createContact(CreateContactTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createContact--TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:34 IST" name="logout" finished-at="2023-01-16T15:20:35 IST" duration-ms="1189" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--logout from application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:35 IST" name="login" finished-at="2023-01-16T15:20:37 IST" duration-ms="2188" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--login to application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createContact()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:37 IST" name="createContact" finished-at="2023-01-16T15:20:40 IST" duration-ms="2958" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg_TestCases.CreateContactTest.createContact(CreateContactTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createContact--TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:41 IST" name="logout" finished-at="2023-01-16T15:20:42 IST" duration-ms="1124" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--logout from application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:42 IST" name="login" finished-at="2023-01-16T15:20:44 IST" duration-ms="1814" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--login to application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createOrgRecycleBin()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:20:44 IST" name="createOrgRecycleBin" finished-at="2023-01-16T15:21:00 IST" duration-ms="16321" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[createOrgRecycleBin--TestScript execution started]]>
            </line>
            <line>
              <![CDATA[createOrgRecycleBin--TestScript execution successful]]>
            </line>
          </reporter-output>
        </test-method> <!-- createOrgRecycleBin -->
        <test-method is-config="true" signature="logout()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:21:00 IST" name="logout" finished-at="2023-01-16T15:21:04 IST" duration-ms="4133" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--logout from application!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closelaunchBrowser()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:21:04 IST" name="closelaunchBrowser" finished-at="2023-01-16T15:21:04 IST" duration-ms="272" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--browser closed!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- closelaunchBrowser -->
        <test-method is-config="true" signature="dbDisconnect()[pri:0, instance:testNg_TestCases.CreateContactTest@5460cf3a]" started-at="2023-01-16T15:21:05 IST" name="dbDisconnect" finished-at="2023-01-16T15:21:05 IST" duration-ms="4" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[--db disconnected!!!--]]>
            </line>
          </reporter-output>
        </test-method> <!-- dbDisconnect -->
      </class> <!-- testNg_TestCases.CreateContactTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
